use crate::memory::dramsim3_wrapper::dramsim3_wrapper;
use crate::memory::mem_portal::{dram_portal, portal_mode, portal_req};
use crate::CPU;
use crate::DSIM3_CFG_PATH;
use crate::DSIM3_OUT_DIR;

const BATCH_SZ: u64 = 0;

#[derive(Clone, Copy)]
enum EngineMode {
    PIM,
    HOST,
    switch_delay,
}

/*
 *
 * TODO
 * Engine want to support both sim_cpu access dram and host access dram, ownership are coordinated
 * through schedule()
 *
 * The way I am planning to handle this problem is create a FIFO model between Engine.dsim3 and
 * sim_cpu.
 *
 * Ideally, sim_cpu and Engine itself will try to submit memory request into dsim3 and check if one
 * of the submitted requst are being fulfilled(or the whole simulator has been drained)
 *
 * However, sim_cpu have to submit the requst inside MEM_stop_FSM instead of actual stage. In this
 * case, I want:
 * 1. two shared struct called cpu_host_ports and dram_ports.
 * 2. cpu_host_port will have tx and rx. cpu_host_port.tx is the place where cpu or host submit
 *    memory request, and cpu_host_ports.rx is the place where cpu/host to see what request has been
 *    completed in.
 * 3. Only one entity(either CPU or host) can submit int one cpu_host_port, so there's no need to
 *    worry about concurrent access. This is guaranteed by scheduler
 * 4. Engine.tick() will need to:
 *      4.1: Obtain what dram_req being completed through last cycle from dsim3, fill them into
 *        cpu_host_port.rx
 *      4.2: Ticking CPU.tick(). CPU.tick() will potentially run MEM_stop_FSM will read from rx port.
 *          If it see the requests it's stopping for, it will unblock
 *          4.2.1: MEM_stop_FSM now contain STALL, Writeback, Release, and Idle. STALL is the place
 *            where memory hold actually happen.
 *          4.2.2: Split STALL into two phase, Submit and Stall. Submit will submit the address from
 *            pipeline, the read/write, and the is_pim flag into cpu_host_port.tx, then it will switch
 *            to Stall to check if it see cpu_host_port.rx
 *      4.3: move the new requests generated by cpu.tick() inside cpu_host_port.tx into
 *        dram_ports.rx
 *      4.4: tick dsim3.tick() so it will consume what's input
 *
 * 5. scheculer() implement the switch model which guarantee only one party can own dsim3 at one
 *    time, and it guarantee the tx and rx are fully drained between they are switching
 *
 */
pub struct Engine {
    sim_cpu: CPU,
    host_pool: Vec<portal_req>,
    dram_port: dram_portal,
    dsim3: dramsim3_wrapper,
    active_port_drained: bool,
    //Following are scheduler internal variables
    mode: EngineMode,
    next_mode: EngineMode,
    coming_from_mode: EngineMode,
    PIM_tick_watermark: u64,
    PIM_tick_rec: u64,
    MEM_req_watermarkL: u64,
    MEM_tick_rec: u64,
}

impl Engine {
    pub fn new() -> Self {
        let dram_port = dram_portal::new();

        Self {
            sim_cpu: CPU::new_with_dram_port(dram_port.clone()),
            dram_port,
            host_pool: Vec::new(),
            dsim3: dramsim3_wrapper::new(DSIM3_CFG_PATH, DSIM3_OUT_DIR, 0, 0, 0, 0),
            active_port_drained: true,
            mode: EngineMode::PIM,
            next_mode: EngineMode::switch_delay,
            coming_from_mode: EngineMode::PIM,
            PIM_tick_watermark: 0,
            PIM_tick_rec: 0,
            MEM_req_watermarkL: BATCH_SZ,
            MEM_tick_rec: 0,
        }
    }

    pub fn get_cpu(&mut self) -> &mut CPU{
        &mut self.sim_cpu
    }

    pub fn get_dram_port(&mut self) -> &mut dram_portal{
        &mut self.dram_port
    }

    fn switch(&mut self, from: EngineMode) {
        if let EngineMode::PIM = from {
            self.PIM_tick_rec = 0;
            self.next_mode = EngineMode::switch_delay;
            self.coming_from_mode = EngineMode::PIM;
        } else if let EngineMode::HOST = from {
            self.PIM_tick_watermark = self.MEM_tick_rec;
            self.MEM_tick_rec = 0;
            self.next_mode = EngineMode::switch_delay;
            self.coming_from_mode = EngineMode::HOST;
        } else {
            if let EngineMode::PIM = self.coming_from_mode {
                self.next_mode = EngineMode::HOST;
                self.coming_from_mode = EngineMode::switch_delay;
                self.dram_port.set_mode(portal_mode::HOST);
            } else if let EngineMode::HOST = self.coming_from_mode {
                self.next_mode = EngineMode::PIM;
                self.coming_from_mode = EngineMode::switch_delay;
                self.dram_port.set_mode(portal_mode::PIM);
            } else {
                panic!("Cannot switch() from switch_delay to switch_delay");
            }
        }
    }
    /*
     *Host -> SW_stale -> PIM -> SW_stale -> Host
     */
    pub fn schedule(&mut self) {
        match self.mode {
            EngineMode::PIM => {
                // if self.PIM_tick_watermark <= self.PIM_tick_rec {
                //     self.sim_cpu.signal_pause(); //Signal sim_cpu to stop
                //     self.switch(EngineMode::PIM);
                // } else {
                //     self.PIM_tick_rec += 1;
                // }
                self.PIM_tick_rec += 1;
            }
            EngineMode::HOST => {
                while let Some(req) = self.host_pool.pop() {
                    self.dram_port.submit(req);
                    self.active_port_drained = false;
                    self.MEM_tick_rec += 1;

                    if self.MEM_tick_rec > self.MEM_req_watermarkL {
                        self.sim_cpu.signal_resume();
                        self.switch(EngineMode::HOST);
                        break;
                    }
                }
            }
            EngineMode::switch_delay => {
                if let EngineMode::PIM = self.coming_from_mode {
                    if self.sim_cpu.ready4signal()
                        && self.active_port_drained
                        && self.dsim3.is_drained()
                    {
                        self.switch(EngineMode::switch_delay);
                    }
                    //Otherwise stay at switch_delay mode
                } else if self.active_port_drained && self.dsim3.is_drained() {
                    self.switch(EngineMode::switch_delay);
                }
            }
        }
    }

    pub fn host_push_req(&mut self, req: portal_req) {
        self.host_pool.push(req);
    }

    fn drain_active_port_to_dram(&mut self) {
        self.active_port_drained = true;

        loop {
            let Some(req) = self.dram_port.get_one_req() else {
                break;
            };

            let is_pim = req.is_pim();
            let is_write = !req.is_read();
            let addr = req.get_addr();

            if self.dsim3.WillAcceptTransaction(addr, is_write) {
                self.dsim3.AddTransactionReq(req);
            } else {
                if is_pim {
                    self.dram_port.submit(portal_req::PIM_REQ { req });
                } else {
                    self.dram_port.submit(portal_req::HOST_REQ { req });
                }

                self.active_port_drained = false;
                break;
            }
        }
    }


    pub fn tick(&mut self) {
        self.sim_cpu.tick();// This tick will eat previous commited dram_req or generate new dram_req
        self.drain_active_port_to_dram();

        for req in self.dsim3.ClockTick() {
            self.dram_port.complete(req);
        }

        self.schedule();
        self.mode = self.next_mode;
    }
}
